server:
  port: 8889
eureka:
  client:
    service-url:
      defaultZone: 'http://eureka1:8888/eureka/,http://eureka2:8886/eureka/'
    healthcheck:
      enabled: true
spring:
  application:
    name: 'config'
  rabbitmq:
    host: 10.16.0.202
    port: 5672
    username: superrd
    password: superrd
  cloud:
    config:
      server:
        git:
          uri: 'https://gitee.com/lhhxb/SpringcloudConfig'
        #  uri: 'https://github.com/FurionCS/SpringcloudConfig'
          search-paths: 'shop'
          password: '115599abc'
          username: 'wuhanligong110'
      label: master
encrypt:
 # key: '*&3loa#@9no_0*(!'
  key-store:
    location: server.jks
    password: letmein
    alias: mytestkey
    secret: changeme

security:
  basic:
   enabled: true
  user:
    name: cs
    password: 123456
management:
  security:
    enabled: false
